title: "Spurt! Empire Games"
description: "An engaging strategy board game where your strategy shapes success."
theme: minima
baseurl: "Spurt-Empire-Games" # Leave empty for root of GitHub Pages
url: "https://emediongfrancis.github.io/spurt-empire-games"

# Social media and contact details
social:
  twitter: spurt_empire
  facebook: spurtgames

# Navigation links
nav_links:
  - name: "Home"
    link: "/"
  - name: "About the Game"
    link: "/about"
  - name: "Features"
    link: "/features"
  - name: "Purchase"
    link: "/purchase"
  - name: "Contact"
    link: "/contact"
